{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "snapwatch.fullname" . }}-clusterrole
  labels:
    {{- include "snapwatch.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]

  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "watch"]

  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "snapwatch.fullname" . }}-clusterrolebinding
  labels:
    {{- include "snapwatch.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "snapwatch.fullname" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ include "snapwatch.serviceAccountName" . }}
    namespace: {{ include "snapwatch.namespace" . }}
{{- end }}
