---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snap-watch
  namespace: snap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snap-watch-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]

  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "watch"]

  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments"]
    verbs: ["get"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: snap-watch-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: snap-watch-clusterrole
subjects:
  - kind: ServiceAccount
    name: snap-watch
    namespace: snap