apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: snap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      snap.weaversoft.io/snap: "true"   # <-- match the handler
      # snap.weaversoft.io/mutated: "false"   # <-- match the handler
  template:
    metadata:
      labels:
        app: nginx
        snap.weaversoft.io/snap: "true" # <-- required
        # snap.weaversoft.io/mutated: "false" # <-- required
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:stable
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          securityContext:
            runAsNonRoot: true