services:
  snapapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snapapi
    stop_grace_period: 2s
    privileged: true
    cap_add:
    - SYS_ADMIN
    group_add:
      - "0"  # root group
      - "998"  # crio group
      - "999"  # podman group
    security_opt:
      - label=disable
    ports:
      - "8000:8000"
    environment:
      # SnapApi configuration
      - SNAP_ORIGINS=http://localhost:3000,http://localhost:8080,http://192.168.33.209:3000,*
      - SNAP_API_URL=http://192.168.130.1:8000
      # SnapWatcher operator configuration
      - WATCHER_CLUSTER_NAME=crc
      - WATCHER_MODE=compose
    volumes:
      # Mount src folder for development
      - ./src:/app:Z 
      # Mount checkpoint storage
      - snapapi-checkpoints:/app/checkpoints
    networks:
      - snap-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  snapui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snapui
    ports:
      - "0.0.0.0:3000:8080"
    environment:
      # API configuration
      - API_URL=${API_URL:-http://localhost:8000}
      - WS_URL=${WS_URL:-ws://localhost:8000}
      
      # React app configuration
      - REACT_APP_USERNAME=${REACT_APP_USERNAME:-admin}
      - REACT_APP_PASSWORD=${REACT_APP_PASSWORD:-admin}
    volumes:
      # Mount src folder for development (optional)
      - ./src:/app:Z
    networks:
      - snap-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


volumes:
  snapapi-checkpoints:
    driver: local
  snapui-build:
    driver: local

networks:
  snap-network:
    driver: bridge
