apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "simple-deployment"
  template:
    metadata:
      labels:
        app: "simple-deployment"
        snap.weaversoft.io/snap: "true"
    spec:
      runtimeClassName: runc
      containers:
      - name: time-loop
        image: busybox:stable
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true;  do     date;   sleep       1 ; done
        imagePullSecrets:
        - name: regcred