apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxOTIuMTY4LjMzLjIwNDo4MDgyIjp7InVzZXJuYW1lIjoiazhzIiwicGFzc3dvcmQiOiJrOHMiLCJhdXRoIjoiYXpoek9tczRjdz09In19fQ==
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson