apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "demo-deployment-test"
  template:
    metadata:
      labels:
        app: "demo-deployment-test"
        snap.weaversoft.io/snap: "true"
    spec:
      containers:
      - name: time-loop
        image: busybox:stable
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do  date;  sleep     1; done
        imagePullSecrets:
        - name: nexus-registry-secret 