{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "snapui.fullname" . }}-route
  labels:
    {{- include "snapui.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "snapui.fullname" . }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
{{- end }}
