apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snap-operator-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
