{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "snapwatcher.namespace" . }}
  labels:
    {{- include "snapwatcher.labels" . | nindent 4 }}
{{- end }}
