---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snap-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snap-operator-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: snap-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: snap-operator-role
subjects:
- kind: ServiceAccount
  name: snap-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snap-operator
  namespace: default
  labels:
    app: snap-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snap-operator
  template:
    metadata:
      labels:
        app: snap-operator
    spec:
      serviceAccountName: snap-operator
      containers:
      - name: operator
        image: snap-operator:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LOG_LEVEL
          value: "INFO"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snap-operator-config
  namespace: default
data:
  log-level: "INFO"
